<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-LMN0PRA" failures="2" tests="12" name="Edge Testing " time="84.288" errors="0" timestamp="2024-07-26T03:19:20 IST">
  <testcase classname="com.factorial.testCases.TC01_Validate_UIElements" name="validateUI" time="0.518"/>
  <testcase classname="com.factorial.testCases.TC02_ValidatePlaceholder" name="verifyPlaceholder" time="0.281"/>
  <testcase classname="com.factorial.testCases.TC02_ValidatePlaceholder" name="verifyTitle" time="0.176">
    <failure type="java.lang.AssertionError" message="expected [Factorial] but found [Factoriall]">
      <![CDATA[java.lang.AssertionError: expected [Factorial] but found [Factoriall]
at com.factorial.pagesObjects.HomePage.title(HomePage.java:70)
at com.factorial.testCases.TC02_ValidatePlaceholder.verifyTitle(TC02_ValidatePlaceholder.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyTitle -->
  <testcase classname="com.factorial.testCases.TC02_ValidatePlaceholder" name="verifyURL" time="0.171"/>
  <testcase classname="com.factorial.testCases.TC03_DataDrivenTesting" name="factorialDDT" time="3.961"/>
  <testcase classname="com.factorial.testCases.TC03_DataDrivenTesting" name="factorialDDT" time="4.489"/>
  <testcase classname="com.factorial.testCases.TC03_DataDrivenTesting" name="factorialDDT" time="3.461"/>
  <testcase classname="com.factorial.testCases.TC03_DataDrivenTesting" name="factorialDDT" time="3.548"/>
  <testcase classname="com.factorial.testCases.TC03_DataDrivenTesting" name="factorialDDT" time="3.499"/>
  <testcase classname="com.factorial.testCases.TC03_DataDrivenTesting" name="factorialDDT" time="3.445"/>
  <testcase classname="com.factorial.testCases.TC03_DataDrivenTesting" name="factorialDDT" time="4.656"/>
  <testcase classname="com.factorial.testCases.TC04_PrivacyBug" name="bug" time="0.619">
    <failure type="java.lang.AssertionError" message="expected [This is the privacy document. We are not yet ready with it. Stay tuned!] but found [This is the terms and conditions document. We are not yet ready with it. Stay tuned!]">
      <![CDATA[java.lang.AssertionError: expected [This is the privacy document. We are not yet ready with it. Stay tuned!] but found [This is the terms and conditions document. We are not yet ready with it. Stay tuned!]
at com.factorial.pagesObjects.HomePage.privacyBug(HomePage.java:114)
at com.factorial.testCases.TC04_PrivacyBug.bug(TC04_PrivacyBug.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- bug -->
</testsuite> <!-- Edge Testing  -->
